Repository Radio-Premium/RadioPremium-Whisper, pull requests merged in 2025-06, with the labels that each got.

#4 feat: Whisper 서버에서 스트리밍 URL 수신 처리 기능 구현
  app.py
  routes/transcribe.py
Labels: ✨feat

#6 feat: Whisper 기반 라디오 실시간 자막 추출 로직 구현
  requirements.txt
  services/whisper_service.py
Labels: ✨feat

#10 feat: Socket 전송 시 userId 포함 및 멀티 유저 대응 구현
  routes/transcribe.py
  services/whisper_service.py
Labels: ✨feat

#16 feat: 사용자의 Whisper 스트리밍 프로세스 종료 기능 구현
  app.py
  requirements.txt
  routes/stop.py
  services/process_registry.py
  services/whisper_service.py
Labels: ✨feat

#18 fix: 사용자 채널 이동 후 광고 감지 및 복귀 로직 에러 해결을 위한 channelId 추가
  routes/transcribe.py
  services/whisper_service.py
Labels: 🔧fix

#22 feat: ML 도입
  .gitignore
  app.py
  requirements.txt
  services/constants.py
  services/predict_ad.py
  services/predict_cli_ad.py
  services/train/train_logistic_regression_ad_classifier.py
  services/train/train_xgboost_ad_classifier.py
  services/whisper_service.py
Labels: ✨feat

#24 chore: 모델 파일 커밋을 위해 .gitignore 수정
  .gitignore
  models/ad_classifier.pkl
Labels: 💡chore

#26 refactor: Whisper 경로 및 메서드 구조 정리
  routes/stop.py
  routes/transcribe.py
Labels: 🛠️refactor
